---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
annotations:
  pipelines.openshift.io/on-target-branch: [main]
  pipelines.openshift.io/on-event: [pull-request]
  # pipelines.openshift.io/on-tag: [1.0] TODO: tags
metadata:
  name: pipeline-scratch-my-back
spec:
  workspaces:
  - name: source
  params:
    - name: repo_url
    - name: revision
  tasks:
    - name: task-spec
      taskSpec:
        steps:
          - name: task-spec
            image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
            script: |
              echo "Hello from taskSpec"
              exit 1

    - name: task-from-tektondir
      taskRef:
        name: task-from-tektondir

    - name: task-from-remote
      taskRef:
        name: task-remote

    - name: task-referenced-internally
      taskRef:
        name: task-referenced-internally
#    - name: git-clone-from-catalog
#      taskRef:
#        name: git-clone
#      params:
#        - name: url
#          value: $(params.repo_url)
#        - name: revision
#          value: $(params.revision)
#      workspaces:
#        - name: output
#          workspace: source
